### Probar req cualquiera
GET http://localhost:1234/

### CATEGORIAS

### Crear una nueva categoria
POST http://localhost:1234/api/categorias HTTP/1.1
content-type: application/json

{
  "nombre": "Cooler"
}

### Obtener una unica categoria por id (ej: 1)
GET http://localhost:1234/api/categorias/1

### Obtener categorias por nombre (ej: Cool)
GET http://localhost:1234/api/categorias?nombre=Cool

### PROVEEDORES

### Crear un nuevo proveedor
POST http://localhost:1234/api/proveedores HTTP/1.1
content-type: application/json

{
  "nombre": "Juan Perez",
  "mail": "raulperez@prueba.com"
}

### Obtener un unico proveedor por id (ej: 1)
GET http://localhost:1234/api/proveedores/1

### Obtener todas las ordenes de un proveedor por id (ej: 1)
GET http://localhost:1234/api/proveedores/1/ordenes

### Obtener proveedores por nombre (ej: Raul)
GET http://localhost:1234/api/proveedores?nombre=Raul

### PRODUCTOS

### Obtener todos los productos
GET http://localhost:1234/api/productos/

### Obtener productos por nombre del producto (ej: Queso)
GET http://localhost:1234/api/productos?nombre=Queso

### Crear un nuevo producto
POST http://localhost:1234/api/productos HTTP/1.1
content-type: application/json

{
  "nombre": "Queso",
  "descripcion": "Queso de cabra",
  "proveedorId": 1,
  "stockActual": 10,
  "categoriaId": 1
}

### Modificar un producto existente (ej: 1)
PUT http://localhost:1234/api/productos/1

### Eliminar un producto existente (ej: 1)
DELETE http://localhost:1234/api/productos/1

### ORDENES

### Obtener una unica orden por id (ej: 1)
GET http://localhost:1234/api/ordenes/1

### Obtener ordenes por fecha minima de generacion (ej: date?)
GET http://localhost:1234/api/ordenes?minFechaGen= date?

### Obtener todos las ordenes de un unico proveedor por id (ej: 1)
GET http://localhost:1234/api/ordenes/proveedor/1

### Crear una nueva orden
POST http://localhost:1234/api/ordenes HTTP/1.1
content-type: application/json

{
  "fechaGeneracion": "2021-05-01T00:00:00.000Z",
  "fechaRecepcion": "2021-05-01T00:00:00.000Z",
  "esCancelada": false,
  "proveedorId": 1
}

### Modificar una orden existente (ej: 1)
PUT http://localhost:1234/api/ordenes/1

### Modificar solo un campo de una orden existente (ej: 1)
PATCH http://localhost:1234/api/ordenes/1
