### Probar req cualquiera
GET http://localhost:1234/

### CATEGORIAS

### Crear una nueva categoria
POST http://localhost:1234/api/categorias HTTP/1.1
content-type: application/json

{
  "nombre": "Categoria3"
}

### Obtener todas las categorias
GET http://localhost:1234/api/categorias/

### Obtener una unica categoria por id (ej: 1)
GET http://localhost:1234/api/categorias/1

### Obtener categorias por nombre (ej: Cool)
GET http://localhost:1234/api/categorias?nombre=Cool

### PROVEEDORES

### Crear un nuevo proveedor
POST http://localhost:1234/api/proveedores HTTP/1.1
content-type: application/json

{
  "nombre": "Jose Rodriguez",
  "mail": "joserodriguez@gmail.com"
}

### Obtener todos los proveedores
GET http://localhost:1234/api/proveedores/

### Obtener un unico proveedor por id (ej: 1)
GET http://localhost:1234/api/proveedores/1

### Obtener todas las ordenes de un proveedor por id (ej: 1)
GET http://localhost:1234/api/proveedores/1/ordenes

### Obtener proveedores por nombre (ej: Raul)
GET http://localhost:1234/api/proveedores?nombre=Jos

### Obtener proveedores por mail (ej: raulperez@prueba)
GET http://localhost:1234/api/proveedores?mail=raulperez@prueba.com

### PRODUCTOS

### Obtener todos los productos
GET http://localhost:1234/api/productos/

### Crear un nuevo producto
POST http://localhost:1234/api/productos HTTP/1.1
content-type: application/json

{
  "nombre": "Pepsi",
  "descripcion": "Gaseosa",
  "proveedorId": 1,
  "stockActual": 25,
  "categoriaId": 1
}

### Obtener productos por nombre del producto (ej: Pan)
GET http://localhost:1234/api/productos?nombre=Pan

### Obtener productos por nombre del proveedor (ej: Jose)
GET http://localhost:1234/api/productos/proveedor/Jose

### Obtener productos por nombre de la categoria (ej: Tremendukis)
GET http://localhost:1234/api/productos/categoria/Categoria1

### Obtener productos por stock actual (ej: 10)
GET http://localhost:1234/api/productos/stock/10

### Modificar un producto existente (ej: 1)
PUT http://localhost:1234/api/productos/1 HTTP/1.1
content-type: application/json

{
  "nombre": "Coca Cola",
  "descripcion": "Gaseosa!",
  "proveedorId": 1,
  "stockActual": 5,
  "categoriaId": 1
}

### Eliminar un producto existente (ej: 1)
DELETE http://localhost:1234/api/productos/1

### ORDENES

### Obtener una unica orden por id (ej: 1)
GET http://localhost:1234/api/ordenes/1

### Obtener ordenes por fecha minima de generacion (ej: date?)
GET http://localhost:1234/api/ordenes?minFechaGen= date?

### Obtener todos las ordenes de un unico proveedor por id (ej: 1)
GET http://localhost:1234/api/ordenes/proveedor/1

### Crear una nueva orden
POST http://localhost:1234/api/ordenes HTTP/1.1
content-type: application/json

{
  "fechaGeneracion": "2021-05-01T00:00:00.000Z",
  "fechaRecepcion": null,
  "esCancelada": false,
  "proveedorId": 1,
  "detalles": [
    {
      "productoId": 1,
      "cantidad": 10,
      "precio": 100
    },
    {
      "productoId": 2,
      "cantidad": 5,
      "precio": 200
    }
  ]
}

### Modificar una orden existente (ej: 1)
PUT http://localhost:1234/api/ordenes/1 HTTP/1.1
content-type: application/json

{
  "fechaGeneracion": "2021-05-01T00:00:00.000Z",
  "fechaRecepcion": null,
  "esCancelada": false,
  "proveedorId": 1,
  "detalles": [
    {
      "productoId": 1,
      "cantidad": 20,
      "precio": 4500
    },
    {
      "productoId": 2,
      "cantidad": 10,
      "precio": 3000
    }
  ]
}

### Modificar solo un campo de una orden existente (ej: 1)
PATCH http://localhost:1234/api/ordenes/1
